-- Фінанси CRM-угод для черги відвантажень і обліку рентабельності

ALTER TABLE public.crm_orders
  ADD COLUMN IF NOT EXISTS total_amount numeric,
  ADD COLUMN IF NOT EXISTS marge_amount numeric;

COMMENT ON COLUMN public.crm_orders.total_amount IS
  'Сума угоди з KeepinCRM (total_amount), грн';
COMMENT ON COLUMN public.crm_orders.marge_amount IS
  'Маржа угоди з KeepinCRM (marge_amount), грн';

CREATE TABLE IF NOT EXISTS public.crm_shipped_deal_metrics (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  crm_id text NOT NULL,
  customer_name text NOT NULL DEFAULT '',
  total_amount numeric NOT NULL DEFAULT 0,
  marge_amount numeric NOT NULL DEFAULT 0,
  shipment_date date NOT NULL,
  shipped_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_crm_shipped_deal_metrics_shipment_date
  ON public.crm_shipped_deal_metrics (shipment_date DESC);

CREATE INDEX IF NOT EXISTS idx_crm_shipped_deal_metrics_crm_id
  ON public.crm_shipped_deal_metrics (crm_id);

COMMENT ON TABLE public.crm_shipped_deal_metrics IS
  'Знімок суми/маржі CRM-угоди в момент відвантаження з черги (для статистики рентабельності)';

ALTER TABLE public.crm_shipped_deal_metrics ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all for authenticated only" ON public.crm_shipped_deal_metrics;
CREATE POLICY "Allow all for authenticated only" ON public.crm_shipped_deal_metrics
  FOR ALL USING (auth.role() = 'authenticated');

GRANT ALL ON public.crm_shipped_deal_metrics TO service_role;
GRANT ALL ON SEQUENCE public.crm_shipped_deal_metrics_id_seq TO service_role;
