-- KeepinCRM: дзеркало активних угод для календаря відвантажень

CREATE TABLE IF NOT EXISTS public.crm_customers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  crm_id text NOT NULL UNIQUE,
  name text NOT NULL,
  phone text,
  email text,
  synced_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.crm_orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  crm_id text NOT NULL UNIQUE,
  customer_id bigint NOT NULL REFERENCES public.crm_customers (id) ON DELETE CASCADE,
  crm_status text,
  crm_created_at timestamptz NOT NULL,
  notes text,
  synced_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_crm_orders_crm_created_at ON public.crm_orders (crm_created_at ASC);

CREATE TABLE IF NOT EXISTS public.crm_order_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id bigint NOT NULL REFERENCES public.crm_orders (id) ON DELETE CASCADE,
  product_id bigint REFERENCES public.products (id) ON DELETE SET NULL,
  crm_product_ref text,
  quantity numeric NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_crm_order_items_order_id ON public.crm_order_items (order_id);

ALTER TABLE public.crm_customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.crm_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.crm_order_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all operations for anon users" ON public.crm_customers;
DROP POLICY IF EXISTS "Allow all for authenticated only" ON public.crm_customers;
CREATE POLICY "Allow all for authenticated only" ON public.crm_customers
  FOR ALL USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Allow all operations for anon users" ON public.crm_orders;
DROP POLICY IF EXISTS "Allow all for authenticated only" ON public.crm_orders;
CREATE POLICY "Allow all for authenticated only" ON public.crm_orders
  FOR ALL USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Allow all operations for anon users" ON public.crm_order_items;
DROP POLICY IF EXISTS "Allow all for authenticated only" ON public.crm_order_items;
CREATE POLICY "Allow all for authenticated only" ON public.crm_order_items
  FOR ALL USING (auth.role() = 'authenticated');

GRANT ALL ON public.crm_customers TO service_role;
GRANT ALL ON public.crm_orders TO service_role;
GRANT ALL ON public.crm_order_items TO service_role;
