CREATE TABLE IF NOT EXISTS public.crm_product_mappings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  crm_product_ref text NOT NULL UNIQUE,
  product_id bigint REFERENCES public.products (id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_crm_product_mappings_product_id
  ON public.crm_product_mappings (product_id);

ALTER TABLE public.crm_product_mappings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all operations for anon users" ON public.crm_product_mappings;
DROP POLICY IF EXISTS "Allow all for authenticated only" ON public.crm_product_mappings;
CREATE POLICY "Allow all for authenticated only" ON public.crm_product_mappings
  FOR ALL USING (auth.role() = 'authenticated');

GRANT ALL ON public.crm_product_mappings TO service_role;
