-- Локальні картки черги відвантаження (лише для розрахунку ETA, без синхронізації з CRM)

CREATE TABLE IF NOT EXISTS public.shipment_planning_orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  queue_rank integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_shipment_planning_orders_queue_rank
  ON public.shipment_planning_orders (queue_rank ASC, id ASC);

CREATE TABLE IF NOT EXISTS public.shipment_planning_order_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id bigint NOT NULL REFERENCES public.shipment_planning_orders (id) ON DELETE CASCADE,
  product_id bigint NOT NULL REFERENCES public.products (id) ON DELETE RESTRICT,
  quantity numeric NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_shipment_planning_order_items_order_id
  ON public.shipment_planning_order_items (order_id);

ALTER TABLE public.shipment_planning_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shipment_planning_order_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all for authenticated only" ON public.shipment_planning_orders;
CREATE POLICY "Allow all for authenticated only" ON public.shipment_planning_orders
  FOR ALL USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Allow all for authenticated only" ON public.shipment_planning_order_items;
CREATE POLICY "Allow all for authenticated only" ON public.shipment_planning_order_items
  FOR ALL USING (auth.role() = 'authenticated');

GRANT ALL ON public.shipment_planning_orders TO service_role;
GRANT ALL ON public.shipment_planning_order_items TO service_role;
